# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hG35yYPZfRyAR-4TU7tGmE8ju98lBYdO
"""

import numpy as np
m=np.array([[1,0,-1],[2,0,2],[8,2,-3]])
ainv = np.linalg.inv(m)
print(ainv)